### ISSUE TITLE
Some status icons don't change

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [vinceliuice/McMojave-circle#10]
Expected behaviour:
1. Open Gnome Tweak Tool
2. Change Icon theme to 'McMojave-circle-blue-dark'
3. All icons change including status icons

Current behaviour:
1. Open Gnome Tweak Tool
2. Change Icon theme to 'McMojave-circle-blue-dark'
3. All icons change except some status icons (battery, audio-volume, system-shutdown)

System:
- Fedora 30
- GNOME Shell 3.32.2
- 03-McMojave-circle-blue.tar.xz | 2019-09-09

**Comment by vinceliuice** [comment]
Can you give a screenshot

**Comment by P1zz4br0etch3n** [comment]
Sure.

First a screenshot with the Numix-Circle theme:
![Bildschirmfoto vom 2019-09-16 17-43-47](https://user-images.githubusercontent.com/9010623/64972493-ac1a7b00-d8a9-11e9-863f-23c6242295bb.png)

And then after changing to McMojave-circle-blue-dark:
![Bildschirmfoto vom 2019-09-16 17-43-59](https://user-images.githubusercontent.com/9010623/64972677-f996e800-d8a9-11e9-9a5b-e8845491e6dc.png)

As you can see, the network status icon changes, but audio and battery stay the same. This started happening a few days ago, probably with an older version of the icon theme. I updated to the latest version but it's still there.

**Comment by vinceliuice** [comment]
You can download and reinstall it from github, maybe reboot your desktop again

**Comment by P1zz4br0etch3n** [comment]
I downloaded the [release](https://github.com/vinceliuice/McMojave-circle/releases/tag/2019_07_12) from github, installed it with the install.sh and rebooted, but the issue is still there.

Also the thumbnails of these icons, e.g. in the status/16 folder, aren't created well in nautilus. Bluetooth works and the icons change in the panel menu, but battery doesn't work. I think it's maybe related to how the svg files are saved? Though I don't have any problems opening the files in Incskape/Gimp/LibreOffice Draw.

![Bildschirmfoto vom 2019-09-17 11-08-39](https://user-images.githubusercontent.com/9010623/65028009-99e91d00-d93b-11e9-92af-766157ed6bd2.png)

Am I the only one facing this issue?

**Comment by P1zz4br0etch3n** [comment]
I was able to reproduce this bug in a VM. Just grab a Fedora 30 image, install it in a VM, install the icon-theme and then do a dnf update. After a reboot some icons are just gone. If one changes the icon theme to something else and back, the icons from the other theme will stay.

**Comment by vinceliuice** [comment]
Did you install this theme with sudo, and after you do dnf update then icon theme just gone?

**Comment by vinceliuice** [comment]
There must be something issue on your system, because you are the only one report this issue, and everything works well on my desktop

**Comment by P1zz4br0etch3n** [comment]
> Did you install this theme with sudo, and after you do dnf update then icon theme just gone?

On my local machine I moved the folders to /usr/share/icons with sudo. But I did it multiple times again since the update and nothing changes. In the VM I just copied them to ~/.icons and there it's the same. One of the updated libraries is librsvg2 but downgrading it doesn't help. Though I think it's something related to how my system renders SVGs.

> There must be something issue on your system, because you are the only one report this issue, and everything works well on my desktop

But it's also in the VM, where I didn't configure anything else. So maybe it's only on Fedora. Which distro are you using?

**Comment by vinceliuice** [comment]
You can install this theme without use sudo, just install it on your user folder, maybe Fedora firewall software delete all files not safety （ not installed from system software manager ）

**Comment by P1zz4br0etch3n** [comment]
I know, but I want it to be available for multiple users. And as I mentioned, in the VM I installed it in the user folder, but after updating it's the same issue. The files are all there, they're just not rendered correctly. Maybe it's how you created the SVGs. I read [here](https://www.reddit.com/r/Inkscape/comments/atag27/help_svg_thumbnails_rendering_incorrectly/egzyvjv/) that not every svg renderer supports every feature. Maybe you used a new feature for some of your icons which aren't supported by the renderer in Fedora. Did you use something different e.g. for battery (not working) compared to network (working) status?

Thanks for your quick replies btw!

**Comment by vinceliuice** [comment]
Only battery icons have this issue on fedora?

**Comment by vinceliuice** [comment]
I used ubuntu and inkscape to make them

**Comment by vinceliuice** [comment]
Are you using last version of Fedora? maybe I can download one to check this issue

**Comment by P1zz4br0etch3n** [comment]
> Only battery icons have this issue on fedora?

The ones I am missing are audio-volume and battery, which should be in the empty space here (top right corner of the screen):

![Bildschirmfoto vom 2019-09-19 09-45-01](https://user-images.githubusercontent.com/9010623/65224745-1149b880-dac4-11e9-9cb1-61cc76c24b0a.png)

Also in the menu battery is missing and the shutdown button is too big:

![Bildschirmfoto vom 2019-09-19 09-50-23](https://user-images.githubusercontent.com/9010623/65224876-58d04480-dac4-11e9-957c-d81dca8de938.png)

And in the places menu the icon for my computer is missing:

![Bildschirmfoto vom 2019-09-19 09-55-22](https://user-images.githubusercontent.com/9010623/65224907-72718c00-dac4-11e9-9f0e-d2a17f83035f.png)

> I used ubuntu and inkscape to make them

The guy on reddit also used Inkscape, maybe it's a similar issue. Weird though that it's only on Fedora.

> Are you using last version of Fedora? maybe I can download one to check this issue

Yes, Fedora 30 is currently the latest version.

**Comment by vinceliuice** [comment]
Ok! I will install Fedora 30 to test my theme

**Comment by P1zz4br0etch3n** [comment]
Thank you so much!

**Comment by bruno-anjos** [comment]
I have the exact same problem in Fedora 30. Just wanted to let you know it is not only affecting you.
![error1](https://user-images.githubusercontent.com/9952231/65250907-41a64c80-daee-11e9-9840-c22ce7ee5303.png)
![error2](https://user-images.githubusercontent.com/9952231/65250912-4539d380-daee-11e9-9782-c235c3c03de1.png)

**Comment by gbegkas** [comment]
Hi, I also have the same issue in Arch with Gnome 3.32.2, so it's not a Fedora only problem. I am missing the battery and shutdown icons. It happened recently after a system update (in the last 2 weeks) without updating the icon theme.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by P1zz4br0etch3n** [comment]
I noticed that a fully up to date Ubuntu has an older version of librsvg2 than Fedora.
Ubuntu has version 2.44.10
On Fedora it's: 2.45.90
Can you please all check which version you have installed? I bet it's related to a change in the lib.

**Comment by bruno-anjos** [comment]
My librsvg2 version is 2.45.90-1

**Comment by gbegkas** [comment]
I have installed 2.46.0 and I downgraded it to 2.44.10 but the issue remains.

**Comment by vinceliuice** [comment]
Can you try tela or other icon theme, I want to know the reason of this issue is icon missing or icon file problem

**Comment by vinceliuice** [comment]
Did you install the last version of github? that's my fedora:
![2019-09-21 08-15-31 的屏幕截图](https://user-images.githubusercontent.com/7604295/65365044-ad043180-dc48-11e9-9ab4-f0489cfe8ee3.png)

**Comment by vinceliuice** [comment]
I don't have this issue, I don't konw why?

**Comment by vinceliuice** [comment]
Sorry my fault! I foget to upload my last version into github

**Comment by vinceliuice** [comment]
Now you can downlad the last version I upload here!

**Comment by P1zz4br0etch3n** [comment]
> Can you try tela or other icon theme, I want to know the reason of this issue is icon missing or icon file problem

Tela works fine for me.



> Did you install the last version of github? that's my fedora:

You installed Fedora 31. I'm on 30, which is the latest stable release.



> Now you can downlad the last version I upload here!

I downloaded the latest version (master branch) but the issue is still there for me.

**Comment by vinceliuice** [comment]
So only fedora 30 have this issue, OK, I'll fedora 30 to test this

**Comment by gbegkas** [comment]
> Can you try tela or other icon theme, I want to know the reason of this issue is icon missing or icon file problem

With Tela icons that didn't work with McMojave are there but I am not so sure that they are the correct icons (I think they are the fallback ones) 

![1](https://user-images.githubusercontent.com/8322948/65373148-469c0500-dc82-11e9-8560-a885058435fe.png)

However on my laptop The wifi icon on the dropdown menu is missing as shown in the picture bellow

![2](https://user-images.githubusercontent.com/8322948/65373156-68958780-dc82-11e9-82b3-c2a00503a300.png)


> Now you can downlad the last version I upload here!

The latest version didn't fix the issue for me too

**Comment by vinceliuice** [comment]
As I know, Gnome 3.34 have changed some icons name, so some icons like battery icons if missing will show the default icon theme

**Comment by vinceliuice** [comment]
![2019-09-22 15-49-30 的屏幕截图](https://user-images.githubusercontent.com/7604295/65384201-c349e480-dd51-11e9-9cbc-5d867e0f033d.png)

**Comment by vinceliuice** [comment]
Also have no issues on fedora 30, Maybe you can download the last version on github (master zip not release file) and reinstall this theme

**Comment by P1zz4br0etch3n** [comment]
Did you do a `dnf update --refresh`?
With a fresh install I'm not having this issue neither. Only after updating all packages. And I already tried the master zip with no luck.

**Comment by vinceliuice** [comment]
DId not update it, I'll try this

**Comment by vinceliuice** [comment]
Fedora 31 beta works well and Fedora works well, I think there must be something issue about librsvg2 update and Fedora 31 fix it

**Comment by P1zz4br0etch3n** [comment]
> Fedora 31 beta works well and Fedora works well, I think there must be something issue about librsvg2 update and Fedora 31 fix it

No, I don't think so, because @gbegkas downgraded to the same version like you have on Ubuntu and still has the issue. And even with the newer version 2.46.0 he had the issue. It must be something else.

> Fedora 31 beta works well and Fedora works well, I think there must be something issue about librsvg2 update and Fedora 31 fix it

So you updated your Fedora 30 and still don't see the issue?

**Comment by vinceliuice** [comment]
I'll update my Fedora and test this issue

**Comment by vinceliuice** [comment]
I update my Fedora 30 and find out that Fadora can not preview svg files if it has title,  so I removed all svg titles as all as I can find to fix this, Now I upload the fixed one on github, you can try it

**Comment by P1zz4br0etch3n** [comment]
Yes! That resolved the issue. Thank you very much!

**Comment by vinceliuice** [comment]
That's all right!
