### ISSUE TITLE
Battery icon not applied in Gnome 3.34

### ISSUE THREAD

**Issue by jgierer12** [vinceliuice/McMojave-circle#11]
I just switched to 3.34, and it seems like McMojave's battery icon is no longer applied and instead it falls back to Gnome's default battery indicator:

![image](https://user-images.githubusercontent.com/4331946/65700752-73845980-e080-11e9-873b-12258690b960.png)

**Comment by vinceliuice** [comment]
Did you download from github, this already fixed at github.

**Comment by jgierer12** [comment]
Oh, I'm really sorry about that. I'm using it from the AUR, seems like the maintainer there has not updated it yet.
