### ISSUE TITLE
--name option doesn't work

### ISSUE THREAD

**Issue by arun54321** [vinceliuice/McMojave-circle#16]
./install.sh -d ~/.local/share/icons --name "mojavaecirclefolder" -c                                                      
ERROR: Unrecognized installation option 'mojavaecirclefolder'.
Try './install.sh --help' for more information.

**Comment by vinceliuice** [comment]
You only need to run this: ./install.sh -n mojavaecirclefolder

**Comment by vinceliuice** [comment]
-c must put before -n

**Comment by arun54321** [comment]
Okay then.
