### ISSUE TITLE
Icon Request: Banshee, Notable, Filezilla, and more.

### ISSUE THREAD

**Issue by fathyar** [vinceliuice/McMojave-circle#19]
- [Banshee](http://banshee.fm/)
- [Notable](https://github.com/notable/notable)
- [Filezilla](https://filezilla-project.org/)
- [Foxit Reader](https://www.foxitsoftware.com/pdf-reader/)
- [calibre](https://calibre-ebook.com/)
- [Anki](https://ankiweb.net/)
- [Xtreme Download Manager](http://xdman.sourceforge.net/)

![icon-request](https://user-images.githubusercontent.com/16875937/72610578-58ed2d80-395a-11ea-927e-212f99c4bbac.gif)

**Comment by axiel7** [comment]
Another request: Google Drive

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
