### ISSUE TITLE
Lollypop only has symbolic icon

### ISSUE THREAD

**Issue by jgierer12** [vinceliuice/McMojave-circle#2]
Hi, thanks for this awesome icon theme!

I've noticed that Lollypop only has a symbolic icon, making its icon in the dash grayscale and slightly oversized:

![image](https://user-images.githubusercontent.com/4331946/59206388-20f06180-8ba5-11e9-9726-402e7329ce85.png)

I would appreciate it if you could include a colored, scaleable icon of Lollypop as well.

**Comment by vinceliuice** [comment]
I'll add the scalable one and fix it, any other icons you want to add?

**Comment by jgierer12** [comment]
Thanks! I would love icons for Notion and Figma, also VSCode has recently [gotten a new icon](https://code.visualstudio.com/updates/v1_35#_updated-visual-studio-code-icon) which would be cool to see reflected in this theme as well.

**Comment by vinceliuice** [comment]
No problem! I'll add them
