### ISSUE TITLE
Battery Icon is hard to read on dark background

### ISSUE THREAD

**Issue by Rapiz1** [vinceliuice/McMojave-circle#27]
## Description
The battery icon is hard to read on some dark plasma themes.

![image](https://user-images.githubusercontent.com/20105061/78515609-06007500-77e9-11ea-98d8-25ecf3eba995.png)
With cursor hovering:
![image](https://user-images.githubusercontent.com/20105061/78515618-10227380-77e9-11ea-8be2-ec174dd41976.png)

It should be battery-100
![image](https://user-images.githubusercontent.com/20105061/78515767-ae163e00-77e9-11ea-927e-9b9834c9da88.png)

The icon is hard to read on both dark and light background.

## Environment
DE: KDE
Plasma Theme: Materia Blur Mono (also confirmed in Breeze Dark, Arc Dark)
Icon Theme: McMojave-circle-blue-dark

**Comment by vinceliuice** [comment]
What is this plugin? it's not plasma default battery plugin

**Comment by Rapiz1** [comment]
`solaar`

**Comment by Rapiz1** [comment]
Maybe it's related to my color scheme?

**Comment by vinceliuice** [comment]
你中国的吗，我看到这个是罗技鼠标的软件

**Comment by Rapiz1** [comment]
是啊

**Comment by vinceliuice** [comment]
那用汉语交流吧，哈哈，我济南的

**Comment by vinceliuice** [comment]
应该是图标主题的事

**Comment by vinceliuice** [comment]
只是我还不确定是使用的哪个图标

**Comment by vinceliuice** [comment]
我安装了一下这个软件，但是我没有罗技鼠标，所以不显示电池图标

**Comment by vinceliuice** [comment]
其他的图标主题也有这个问题吗？

**Comment by Rapiz1** [comment]
Papirus-Dark, Breeze都没有这个问题

**Comment by Rapiz1** [comment]
https://github.com/pwr-Solaar/Solaar/blob/2a94cc9233d000bab8d9864631dd23fcb81137bd/lib/solaar/ui/icons.py#L95-L101
这些是图标选择逻辑 我正在看

**Comment by vinceliuice** [comment]
好的，我对比一下Papirus-Dark的图标，看怎么修复，我看显示的那个图标是短一些的电池图标，应该是battery-full-symbolic.svg这种后面带symbolic的图标，应该这是给gnome桌面使用的图标只能是16x16的尺寸的，所以短一些，而不带symbolic的图标是正常长度的

**Comment by Rapiz1** [comment]
对的。我刚刚通过调试源码发现使用的是`battery-full-symbolic`

**Comment by vinceliuice** [comment]
嗯，知道什么图标了就好办，我再看看Papirus怎么处理的就知道怎么修复了

**Comment by vinceliuice** [comment]
我更新了一下，你试试最新的

**Comment by Rapiz1** [comment]
![image](https://user-images.githubusercontent.com/20105061/78782912-5ccaa200-79d5-11ea-8c03-8db6e9fc536f.png)
解决了，谢谢！很快，很厉害！

**Comment by vinceliuice** [comment]
不客气
