### ISSUE TITLE
Icon Request: Viber, Reaper and Mudita24

### ISSUE THREAD

**Issue by a-parhom** [vinceliuice/McMojave-circle#28]
- [Viber](https://www.viber.com/)
- [Reaper](http://reaper.fm/)
- [Mudita24](https://github.com/NielsMayer/mudita24) Original icon: 
![mudita24](https://user-images.githubusercontent.com/13824167/78926706-2f015e00-7aa6-11ea-98c6-059583024e31.png)

![icons](https://user-images.githubusercontent.com/13824167/78926300-85ba6800-7aa5-11ea-988b-5bb6e5ce975b.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by Hoking007** [comment]
Is this latte-dock？
very beautiful！

**Comment by a-parhom** [comment]
Yes, it's Latte Dock.
