### ISSUE TITLE
[Feature Request] Pamac gnome extension indicator icon

### ISSUE THREAD

**Issue by ceyhunn** [vinceliuice/McMojave-circle#3]
Pamac gnome extension indicator icon size is bigger:
![Screenshot from 2019-06-15 13-53-25](https://user-images.githubusercontent.com/5506156/59549950-06880080-8f76-11e9-86b4-1f8acf4b64df.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by ceyhunn** [comment]
Thank you so much...
