### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by liulitchi** [vinceliuice/McMojave-circle#33]
还是用中文好了，浣衣尘的大名，多年前早有耳闻。我用的是 Debian-Mate，一直用的是 matcha 主题 。

今天测试了一下这个主题，发现 需要更新一下 Retext 和 Aegisub 两个图标。另外就是 xterm 和 uxterm 的图标似乎也需要更新一下，虽然这两个终端基本都被大家无视，可它们毕竟是 Xorg 依赖的软件，谁也绕不开。

再次感谢大佬的工作。

**Comment by vinceliuice** [comment]
好的！没问题👌

**Comment by vinceliuice** [comment]
添加了
