### ISSUE TITLE
Nautilus starred files icon missing

### ISSUE THREAD

**Issue by krieghof** [vinceliuice/McMojave-circle#35]
In nautilus you can star your favorite files, but the starred icon is the same for starred files and not starred files.

The applications folder is starred, but the star icon has no visible difference
![Screenshot from 2020-04-30 13-31-39](https://user-images.githubusercontent.com/17674464/80705739-3afda000-8ae7-11ea-8d41-fba9f70fe5cd.png)

Great icon theme keep up the good work thank you

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed ！
