### ISSUE TITLE
Icon Request for Zoom, Auryo, and Burp Suite

### ISSUE THREAD

**Issue by mugi789** [vinceliuice/McMojave-circle#39]
### Icon Zoom
![gambar](https://user-images.githubusercontent.com/32443765/84761266-697dfe80-aff3-11ea-880c-2f2d2b2f5ab3.png)

### Icon Auryo
![gambar](https://user-images.githubusercontent.com/32443765/84761420-94685280-aff3-11ea-8dd5-b09927431d95.png)

### Icon Burp Suite
![gambar](https://user-images.githubusercontent.com/32443765/84761923-5586cc80-aff4-11ea-832e-20db4f100397.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
