### ISSUE TITLE
icon Request

### ISSUE THREAD

**Issue by APakrohk** [vinceliuice/McMojave-circle#4]
Hi Plz Add

Persepolis Download Manager : https://persepolisdm.github.io
KTorrent : https://kde.org/applications/internet/org.kde.ktorrent
Godot Engine : https://godotengine.org
Clementine : https://www.clementine-player.org
kdenlive : https://kdenlive.org/en
Kindd : https://github.com/LinArcX/Kindd

Panel(Active Window Control) : https://github.com/kotelnik/plasma-applet-active-window-control
![screen](https://user-images.githubusercontent.com/27810360/59572587-735ce100-90c3-11e9-81d4-67b091696600.png)

**Comment by vinceliuice** [comment]
no problem

**Comment by APakrohk** [comment]
New update was great
---------------------------------------------------------
brackets : http://brackets.io/

**Comment by vinceliuice** [comment]
Added now!
