### ISSUE TITLE
Icon request for Joplin

### ISSUE THREAD

**Issue by sanwanliu** [vinceliuice/McMojave-circle#45]
Is it possible to add a icon for the Joplin application? 

https://joplinapp.org

Thank you!

![image](https://user-images.githubusercontent.com/23079982/89704249-ce672c80-d984-11ea-85e8-95931e5d4ec0.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added

**Comment by vinceliuice** [comment]
Added
