### ISSUE TITLE
Icon Request for Teams

### ISSUE THREAD

**Issue by felipeneri** [vinceliuice/McMojave-circle#46]
Is it possible to add a icon for the Teams application (Microsoft Teams)?

![request_icon_teams_](https://user-images.githubusercontent.com/15368659/90705981-868cb300-e26a-11ea-94d3-10c737e46ba5.png)

https://www.microsoft.com/pt-br/microsoft-365/microsoft-teams/teams-for-home

Thank you!

**Comment by vinceliuice** [comment]
No problem!
