### ISSUE TITLE
Icon Request (Apps & Suggestion)

### ISSUE THREAD

**Issue by XEmpty** [vinceliuice/McMojave-circle#5]
To Update ( Isn't Good Looks / Old ) : KSystemLog, Yakuake, KDE Partition Manager,  Visual Studio, Filelight.

App Name : Clion
Description : C++ IDE
Webpage (optional) : https://www.jetbrains.com/clion/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284460-ee08cf00-c2b3-11e9-9fa2-191a936770f4.png)

App Name : PhpStorm
Description : Php IDE
Webpage (optional) :https://www.jetbrains.com/phpstorm/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284483-f95bfa80-c2b3-11e9-810f-a7576f16650b.png)

App Name : DataGrip
Description : Database IDE / Management 
Webpage (optional) : https://www.jetbrains.com/datagrip/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284495-011b9f00-c2b4-11e9-837f-75b1e3135d3d.png)

App Name : Lutris
Description : Open Gaming Platform
Webpage (optional) : https://lutris.net/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284510-0a0c7080-c2b4-11e9-84e3-b288e109e944.png)

App Name : Timeshift
Description : System Restore Utility
Webpage (optional) : https://github.com/teejee2008/timeshift
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284530-185a8c80-c2b4-11e9-880c-cd74fdb41181.png)

App Name : Dragon Player
Description : Video Player
Webpage (optional) : https://kde.org/applications/multimedia/org.kde.dragonplayer
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284568-25777b80-c2b4-11e9-8476-e70c233020a7.png)

App Name : Firewalld
Description : Firewall
Webpage (optional) : https://firewalld.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284589-30321080-c2b4-11e9-813d-62a026532911.png)

App Name : Neovim
Description : Text Editor
Webpage (optional) : https://neovim.io/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284927-f1e92100-c2b4-11e9-8b06-787644519d74.png)

App Name : Bleachbit
Description : File Cleaner
Webpage (optional) : https://www.bleachbit.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284648-4d66df00-c2b4-11e9-9bc7-d8e39accb042.png)

App Name : Akonadiconsole
Description : Akonadi Management and Debugging
Webpage (optional) : https://krusader.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63284670-5952a100-c2b4-11e9-8697-c6fb5d19172e.png)

App Name : Krusader
Description : File Manager
Webpage (optional) : https://krusader.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230434-dc202100-c20c-11e9-855f-f302d9fa7252.png)

-------
###

App Name : Krusader Root
Description : File Manager as Root
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230705-b563e980-c210-11e9-8dee-b64ab95f5359.png)

-------
###

App Name : QBittorent
Description : BitTorrent Client
Webpage (optional) :https://www.qbittorrent.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230467-38834080-c20d-11e9-928d-56f91f65e228.png)

-------
### 

App Name : Zeal Docs
Description : Documentation Browser
Webpage (optional) : https://zealdocs.org/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230527-163df280-c20e-11e9-9358-17e6963c28c9.png)

-------
### 

App Name : XMind Zen
Description : Mind Mapping Software
Webpage (optional) : https://www.xmind.net/zen/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230532-20f88780-c20e-11e9-87e9-16cfbd25117a.png)

-------
### 

App Name : ClickUp
Description : Todo Software
Webpage (optional) : https://clickup.com/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230536-2d7ce000-c20e-11e9-8f4d-8e80e572aa49.png)

-------
### 

App Name : OBS Studio
Description : Streaming / Recording Software
Webpage (optional) : https://obsproject.com/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230539-379ede80-c20e-11e9-9fd2-8588666681d2.png)

-------
### 

App Name : Figma
Description : Collaborative interface design tool
Webpage (optional) : https://www.figma.com/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230543-41c0dd00-c20e-11e9-88a0-1d5c910fc6ad.png)

-------
###

App Name : GreenWithEnvy
Description : Provides information, controls the fans and overclocks your NVIDIA video card
Webpage (optional) : https://gitlab.com/leinardi/gwe
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230550-61580580-c20e-11e9-8f0b-777938dbdf31.png)

-------
###

App Name : Kompare
Description : Diff/Patch Frontend
Webpage (optional) : https://kde.org/applications/development/org.kde.kompare
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230552-6c129a80-c20e-11e9-8003-73887050b899.png)

-------
###

App Name : Juk
Description : Music Player
Webpage (optional) : https://kde.org/applications/multimedia/org.kde.juk
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63230549-556c4380-c20e-11e9-8a40-625e3c9c2a23.png)

-------
###

Folders : Vbox, Scripts, Git, Games, Torrents, Development.  ( Like Picture etc.. )
Suggestion : More contrast between folder color and symbol in folder. ( can't see what it is ) .

**Comment by XEmpty** [comment]
Bump

**Comment by vinceliuice** [comment]
No problem! I'll add them

**Comment by XEmpty** [comment]
And one more ! :+1: 

App Name : Irix
Description : Color Scheme Editor
Webpage (optional) : https://irix.app/
Original Icon : ![image](https://user-images.githubusercontent.com/8018061/63325712-ffd98900-c32a-11e9-84a2-461a6118bb04.png)

**Comment by vinceliuice** [comment]
Added now!

**Comment by XEmpty** [comment]
U just add irix icon. From this list. ; ( . But anyway thanks.

**Comment by XEmpty** [comment]
@vinceliuice The icons from the first post have not been added.

**Comment by vinceliuice** [comment]
OK
