### ISSUE TITLE
Icon Request Whatsdesk (Whatsapp Client)

### ISSUE THREAD

**Issue by mugi789** [vinceliuice/McMojave-circle#51]
Icon Request Whatsdesk (Whatsapp Client)

![](https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_60,h_60/https://dashboard.snapcraft.io/site_media/appmedia/2018/06/icon_xBt3roT.png)

Link for download 
- (.deb) https://zerkc.gitlab.io/whatsdesk/
- (snap) https://snapcraft.io/whatsdesk

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
