### ISSUE TITLE
Icon Request: Bitwarden

### ISSUE THREAD

**Issue by RedfinDiver** [vinceliuice/McMojave-circle#56]
Hi! A custom icon for the bitwarden application would be awesome! Now it is only showing a standard icon:
![bw](https://user-images.githubusercontent.com/24232625/113503500-9a073880-9532-11eb-849a-a0f7516b6332.png)

The icon normally is bluish and looks like a shield:
![bwo](https://user-images.githubusercontent.com/24232625/113503580-14d05380-9533-11eb-9044-a50caf0093ab.png)

Thank you for your work!

**Comment by puenka** [comment]
I was recently also annoyed by this icon and just created my own.
You can easily take the svg version of the Bitwarden icon from https://github.com/bitwarden/brand (more specifically [1]) as a starting point. The emblem is available as a vector component from there. I have started from the `apps/scalable/access.svg` from this repo, adjusted the color a bit and replaced the symbol there with the one from the linked icon to create my own and replace the `apps/scalable/bitwarden.svg` (which is only a link at the moment).

I hope that with the referenced icon it's only a few minutes of work for @vinceliuice to do it and add it to the repo in a perfectly consistent style!

[1] https://github.com/bitwarden/brand/blob/master/icons/icon.svg

**Comment by vinceliuice** [comment]
Added
