### ISSUE TITLE
[Question] change default folder color?

### ISSUE THREAD

**Issue by nikolaioak** [vinceliuice/McMojave-circle#59]
Not sure if there is a well known way to do this, but I notice you provide various folder colors in the icons. How would I go about switching to one of the other colors as the default? I believe changing the links within the folder icons (for default-folder, etc) to another color folder doesn't seem to work but I may not be doing it right. I'm on Kubuntu 20.04 if that helps at all. Thanks for this theme, it's awesome!

**Comment by CaptainAsbestos** [comment]
I just checked my own `~/.local/share/icons/` directory and I have multiple colors of the theme downloaded, all of which are visible as options in the Appearances > Icons menu of systemsettings5. Just extract the desired color of icon set you want and move it to that location; if you want it system-wide I imagine that it goes in `/usr/share/icons/`. Hope that helps!

**Comment by nikolaioak** [comment]
Thanks for the follow up @CaptainAsbestos - when I look in my system settings I only have McMojave-circle and McMojave-circle-dark:
![image](https://user-images.githubusercontent.com/44122708/121813599-ad253b80-cc3a-11eb-95e9-e80f22be36cb.png)

I also have the two icon sets in `~/.local/share/icons/` with all the folder colors under `~/.local/share/icons/McMojave-circle-dark/places/scalable/` but not exactly sure what you mean by extract them.

I initially tried editing the links of the "default" icons to a different color (blue, for example) but that didn't seem to work, not sure if there are other files I should do this to:
![image](https://user-images.githubusercontent.com/44122708/121813694-389ecc80-cc3b-11eb-8872-6e8c4f2152c6.png)
![image](https://user-images.githubusercontent.com/44122708/121813747-77348700-cc3b-11eb-8d51-d49358a7d825.png)

**Comment by nikolaioak** [comment]
Thanks for the help again - I figured it out. Made a copy of the default folder color icons and duplicated another color with the name of the defaults (folder.svg, etc). This showed up properly in dolphin when I logged out/in.
