### ISSUE TITLE
how to change titlebar icons

### ISSUE THREAD

**Issue by Pshemas** [vinceliuice/McMojave-circle#61]
I love this icon theme - but with one exception. I'd love to swap window close / minimize / maximize buttons for the ones found in Adwaita dark theme. I've spent an hour trying to find which file corresponds to it and I can't figure it out.

**Comment by vinceliuice** [comment]
`window-maximize-symbolic.svg` `window-minimize-symbolic.svg` `window-close-symbolic.svg` `window-restore-symbolic.svg`

**Comment by Pshemas** [comment]
thank you! that helps a lot.

**Comment by vinceliuice** [comment]
You are welcome!
